on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: true
      head_sha:
        description: 'Head commit SHA that dispatched the workflow'
        required: true

jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Static code analysis step
        uses: betrybe/eslint-linter-action@v2
        id: eslint
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
