on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: true

jobs:
  evaluator_job:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
